# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 03:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grumblr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('age', models.PositiveIntegerField()),
                ('bio', models.CharField(blank=True, default='Write your short bio here.', max_length=420)),
                ('picture', models.ImageField(blank=True, default='', upload_to='profile_pictures')),
                ('follows', models.ManyToManyField(related_name='followees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
